development:
  adapter: postgresql
  encoding: unicode
  database: picture_parser_dev
  pool: 5
  timeout: 5000
<<<<<<< HEAD
  username:
=======
  username: alextsveta2012
>>>>>>> 6ef513d6525c7e2abf98b9037f5d29b57f6b7438
  password:

test:
  adapter: postgresql
  database: picture_parser_test
  pool: 5
  timeout: 5000
<<<<<<< HEAD
  username:
=======
  username: alextsveta2012
>>>>>>> 6ef513d6525c7e2abf98b9037f5d29b57f6b7438
  password:

production:
  adapter: postgresql
  database: picture_parser