development:
  adapter: postgresql
  encoding: unicode
  database: picture_parser_dev
  pool: 5
  timeout: 5000
  username:
  password:

test:
  adapter: postgresql
  database: picture_parser_test
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: postgresql
  database: picture_parser